channels:
- defaults
dependencies:
- pip
- python=3.7
- pip:
  - asn1crypto==1.5.1
  - boto3==1.26.117
  - botocore==1.29.121
  - cfgv==3.3.1
  - charset-normalizer==3.1.0
  - cloudpickle==2.2.1
  - cycler==0.11.0
  - distlib==0.3.6
  - filelock==3.12.0
  - greenlet==2.0.2
  - identify==2.5.23
  - idna==3.4
  - importlib-metadata==6.6.0
  - jmespath==1.0.1
  - joblib==1.2.0
  - kiwisolver==1.4.4
  - llvmlite==0.36.0
  - matplotlib==3.3.4
  - nodeenv==1.7.0
  - numba==0.53.1
  - numpy==1.15.0
  - packaging==23.1
  - pandas==1.0.5
  - pg8000==1.29.4
  - pillow==9.5.0
  - platformdirs==3.4.0
  - praw==7.7.0
  - prawcore==2.3.0
  - pre-commit==2.21.0
  - py4j==0.10.9.5
  - pyarrow==2.0.0
  - pyparsing==3.0.9
  - pyspark==3.3.0
  - python-dateutil==2.8.2
  - pytz==2023.3
  - pyyaml==6.0
  - requests==2.29.0
  - s3transfer==0.6.0
  - scikit-learn==1.0.2
  - scipy==1.5.4
  - scramp==1.4.4
  - seaborn==0.11.2
  - shap==0.41.0
  - six==1.16.0
  - slicer==0.0.7
  - sqlalchemy==1.4.46
  - threadpoolctl==3.1.0
  - tqdm==4.65.0
  - typing-extensions==4.5.0
  - update-checker==0.18.0
  - urllib3==1.26.15
  - virtualenv==20.22.0
  - websocket-client==1.5.1
  - zipp==3.15.0
