name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.7'
    
    - name: Install requirements
      run: pip install -r requirements.txt
      
    - name: Run tests and collect coverage
      run: pytest --cov .
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      
